# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-xml-mapper}
  s.version = "1.0.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stanislav Senotrusov"]
  s.date = %q{2009-11-27}
  s.email = %q{senotrusov@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "lib/ruby-xml-mapper.rb",
     "lib/ruby-xml-mapper/basic_containers.rb",
     "lib/ruby-xml-mapper/file_cache.rb",
     "lib/ruby-xml-mapper/file_cache_item.rb",
     "lib/ruby-xml-mapper/rss.rb",
     "ruby-xml-mapper.gemspec"
  ]
  s.homepage = %q{http://github.com/senotrusov/ruby-xml-mapper}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Mapping XML to Ruby in handy declarative manner}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

